name: Deploy
on:
  push:
    branches:
      - master  
  workflow_dispatch:  
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Dependencias
         run: npm i
       - name: Build
         run: npm run build
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Deploy
         run: echo "Deploying..."
       - name: Deploy Donde
         run: echo "Deployed"
      
      
